import{_ as o}from"./plugin-vue_export-helper-x3n3nnut.js";import{r as n,o as s,c as r,a as t,d as e,b as i,w as c}from"./app-Vtb4Stqz.js";const l={},d=t("p",null,"If you are sure that the user data is correct, but you still get this exception, please check the correctness of the token specified in the settings.",-1);function h(_,f){const a=n("RouterLink");return s(),r("div",null,[t("p",null,[e("An exception may indicate a failed user validation by one of the "),i(a,{to:"/en/docs/validator/"},{default:c(()=>[e("available validators")]),_:1}),e(". And therefore, there is a threat of hacking and/or bypassing the system.")]),d])}const m=o(l,[["render",h],["__file","validation.html.vue"]]);export{m as default};
